Repository knative-extensions/backstage-plugins, pull requests merged in 2024-02, with the labels that each got.

#23 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/S, skip-review

#33 GitHub action to release snapshots of the plugin
  .actrc
  .github/workflows/backstage-release-snapshot.yaml
  README.md
Labels: approved, size/M, lgtm

#35 Update instructions, fix release
  backstage/plugins/knative-event-mesh-backend/.npmignore
  backstage/plugins/knative-event-mesh-backend/README.md
Labels: approved, lgtm, size/S

#38 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#40 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#39 Fix Backstage plugin publishing
  .github/workflows/backstage-release-snapshot.yaml
  .github/workflows/backstage-release.yaml
Labels: approved, lgtm, size/S

#42 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#44 Add a link to a demo repository
  backstage/plugins/knative-event-mesh-backend/README.md
Labels: size/XS, approved, lgtm
