Repository knative-extensions/backstage-plugins, pull requests merged in 2024-04, with the labels that each got.

#48 linting actions added
  .github/workflows/backstage-lint.yaml
  .github/workflows/backstage-release.yaml
  backstage/plugins/knative-event-mesh-backend/package.json
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProcessor.test.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProcessor.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProvider.test.ts
  backstage/yarn.lock
Labels: approved, size/XL, lgtm

#51 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#52 Add labels to eventmesh-backend resources
  backends/config/100-eventmesh/100-clusterrole.yaml
  backends/config/100-eventmesh/200-controller-service-account.yaml
  backends/config/100-eventmesh/201-controller-cluster-role-binding.yaml
Labels: size/XS, approved, lgtm

#54 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#55 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#56 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#57 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
