Repository knative-extensions/backstage-plugins, pull requests merged in 2024-01, with the labels that each got.

#13 Release setup
  .github/workflows/backstage-release.yaml
  .github/workflows/backstage-unit-tests.yaml
  backstage/lerna.json
  backstage/packages/backend/package.json
  backstage/plugins/knative-event-mesh-backend/.npmignore
  backstage/plugins/knative-event-mesh-backend/package.json
  backstage/yarn.lock
  hack/release.sh
  test/presubmit-tests.sh
Labels: approved, size/L, lgtm

#16 Fix release script
  .github/workflows/backstage-release.yaml
Labels: size/XS, approved, lgtm

#6 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
