Repository knative-extensions/backstage-plugins, pull requests merged in 2024-09, with the labels that each got.

#81 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#78 Run NPM package tests before publishing Golang code
  test/e2e-tests.sh
  test/presubmit-tests.sh
Labels: approved, size/M, lgtm

#85 E2E tests for backend security
  backends/tests/e2e/integration_test.go
  backends/tests/e2e/main_test.go
  go.mod
  hack/tools.go
  test/config/eventmesh-backend-user.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/doc.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#87 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#88 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#92 Deduplicate docs, give links to the Knative website
  README.md
  backstage/README.md
  backstage/packages/README.md
  backstage/packages/backend/README.md
  backstage/plugins/README.md
  backstage/plugins/knative-event-mesh-backend/README-dynamic.md
  backstage/plugins/knative-event-mesh-backend/README.md
  event-mesh-plugin-apis-view.png
  event-mesh-plugin-components-view.png
Labels: approved, size/L, lgtm

#90 Fix Slack msg in case of release failure
  .github/workflows/backstage-release.yaml
Labels: approved, lgtm, size/S

#93 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: approved, size/M, lgtm

#94 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review
