Repository knative-extensions/backstage-plugins, pull requests merged in 2024-06, with the labels that each got.

#65 readme changes for ingress configuration
  README.md
  backstage/README.md
Labels: approved, size/M, lgtm

#64 Dynamic plugin
  backstage/packages/backend/package.json
  backstage/plugins/knative-event-mesh-backend/README-dynamic.md
  backstage/plugins/knative-event-mesh-backend/README.md
  backstage/plugins/knative-event-mesh-backend/dist-dynamic/.gitignore
  backstage/plugins/knative-event-mesh-backend/dist-dynamic/package.json
  backstage/plugins/knative-event-mesh-backend/dist-dynamic/yarn.lock
  backstage/plugins/knative-event-mesh-backend/package.json
  backstage/plugins/knative-event-mesh-backend/src/alpha.ts
  backstage/plugins/knative-event-mesh-backend/src/dynamic/index.ts
  backstage/plugins/knative-event-mesh-backend/src/index.ts
  backstage/plugins/knative-event-mesh-backend/src/module.ts
  backstage/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: size/XXL, approved, lgtm

#67 chore: update knative backend plugin for new backend and add docs
  backstage/plugins/knative-event-mesh-backend/README.md
  backstage/plugins/knative-event-mesh-backend/src/module.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProcessor.test.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProcessor.ts
  backstage/yarn.lock
Labels: kind/documentation, approved, kind/cleanup, size/M, lgtm

#68 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#69 Publish dynamic plugin
  .github/workflows/backstage-release-snapshot.yaml
  .github/workflows/backstage-release.yaml
Labels: approved, lgtm, size/S
