Repository knative-extensions/backstage-plugins, pull requests merged in 2024-10, with the labels that each got.

#95 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#96 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/job_sink_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#97 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#99 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#100 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#102 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#103 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#104 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#105 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#107 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#101 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/internal/descopts/options.go
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/doc.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/map_entry.go
  vendor/google.golang.org/protobuf/internal/genid/wrappers.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/codec_unsafe.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/impl/encode.go
  vendor/google.golang.org/protobuf/internal/impl/equal.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_pure.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/equal.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/methods.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_pure.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/runtime/protoiface/methods.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/auth/verifier.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#108 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#109 Update Knative deps & func to release 1.16
  backstage/templates/skeletons/go-cloudevents/go.mod
  backstage/templates/skeletons/go-cloudevents/go.sum
  backstage/templates/skeletons/node-cloudevents/package-lock.json
  backstage/templates/skeletons/node-cloudevents/package.json
  backstage/templates/skeletons/node-http/package-lock.json
  backstage/templates/skeletons/node-http/package.json
  backstage/templates/skeletons/python-cloudevents/test_func.py
  backstage/templates/skeletons/python-flask/requirements.txt
  backstage/templates/skeletons/python-http/func.py
  backstage/templates/skeletons/python-http/test_func.py
  backstage/templates/skeletons/python-wsgi/requirements.txt
  backstage/templates/skeletons/quarkus-cloudevents/README.md
  backstage/templates/skeletons/quarkus-cloudevents/pom.xml
  backstage/templates/skeletons/quarkus-http/README.md
  backstage/templates/skeletons/quarkus-http/pom.xml
  backstage/templates/skeletons/rust-cloudevents/Cargo.lock
  backstage/templates/skeletons/rust-http/Cargo.lock
  backstage/templates/skeletons/springboot-cloudevents/pom.xml
  backstage/templates/skeletons/springboot-cloudevents/src/test/java/echo/SpringCloudEventsApplicationTests.java
  backstage/templates/skeletons/springboot-http/pom.xml
  backstage/templates/skeletons/springboot-http/src/main/resources/application.properties
  backstage/templates/skeletons/typescript-cloudevents/package-lock.json
  backstage/templates/skeletons/typescript-cloudevents/package.json
  backstage/templates/skeletons/typescript-http/package-lock.json
  backstage/templates/skeletons/typescript-http/package.json
  go.mod
  go.sum
  hack/func-version.txt
  vendor/modules.txt
Labels: size/XXL, approved, lgtm

#110 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#111 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#112 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review
