Repository knative-extensions/backstage-plugins, pull requests merged in 2024-05, with the labels that each got.

#58 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#59 Fix build
  backstage/packages/backend/src/plugins/catalog.ts
  backstage/plugins/knative-event-mesh-backend/package.json
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProcessor.test.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProvider.test.ts
Labels: approved, size/M, lgtm

#60 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#61 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, skip-review

#63 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
