Repository knative-extensions/backstage-plugins, pull requests merged in 2025-01, with the labels that each got.

#142 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#145 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#146 Version the API
  backends/pkg/eventmesh/auth/authtokenmiddleware.go
  backends/pkg/eventmesh/v1/api.gen.go
  backends/pkg/eventmesh/v1/broker.go
  backends/pkg/eventmesh/v1/builder.go
  backends/pkg/eventmesh/v1/builder_test.go
  backends/pkg/eventmesh/v1/endpoint.go
  backends/pkg/eventmesh/v1/eventtype.go
  backends/pkg/eventmesh/v1/server.gen.go
  backends/pkg/reconciler/eventmesh/controller.go
  backends/pkg/util/annotations.go
  backends/pkg/util/annotations_test.go
  backends/pkg/util/util.go
  backends/tests/e2e/integration_v1_test.go
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProvider.ts
  hack/generate.go
  hack/oapi-models-config-event-mesh-v1.yaml
  hack/oapi-server-config-event-mesh-v1.yaml
  specs/event-mesh-v1.yaml
Labels: approved, size/L, lgtm

#147 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#148 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#150 Fix release script import
  hack/release.sh
Labels: size/XS, approved, lgtm

#152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#151 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/L, lgtm

#149 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#153 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#154 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#156 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#157 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review
