Repository knative-extensions/backstage-plugins, pull requests merged in 2025-08, with the labels that each got.

#246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#248 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#249 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#250 Update reconciler-test
  backends/tests/e2e/integration_v1_test.go
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#254 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/S, skip-review

#256 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#263 [release-1.19] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#265 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#267 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#270 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#273 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review

#275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, skip-review
