Repository knative-extensions/backstage-plugins, pull requests merged in 2025-04, with the labels that each got.

#189 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#190 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#193 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#192 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#195 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#197 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#198 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#200 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#194 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#201 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#202 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#203 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#204 Fix: Add inmemorychannels resource to ClusterRole
  test/config/eventmesh-backend-user.yaml
Labels: size/XS, approved, lgtm
