Repository knative-extensions/backstage-plugins, pull requests merged in 2025-03, with the labels that each got.

#155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/L, lgtm

#164 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/XXL, skip-review

#167 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#168 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#169 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#170 Upgrade some dependencies
  backstage/package.json
  backstage/yarn.lock
Labels: approved, size/L, lgtm

#174 [release-1.16] MANUAL Upgrade some dependencies
  backstage/package.json
  backstage/yarn.lock
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#166 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#175 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: approved, size/L, lgtm

#176 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#177 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#179 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#180 [main] Upgrade to latest dependencies
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#181 Pin xml-crypto to 2.1.6
  backstage/package.json
  backstage/yarn.lock
Labels: approved, size/M, lgtm

#185 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#186 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
