Repository knative-extensions/backstage-plugins, pull requests merged in 2025-02, with the labels that each got.

#158 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#159 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#161 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#162 [Automated] Update backstage-plugins-eventing nightly
  third_party/eventing-latest/eventing-core.yaml
  third_party/eventing-latest/eventing-crds.yaml
  third_party/eventing-latest/in-memory-channel.yaml
  third_party/eventing-latest/mt-channel-broker.yaml
Labels: size/L, skip-review

#163 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#160 Channels and sources
  backends/pkg/eventmesh/v1/api.ext.go
  backends/pkg/eventmesh/v1/api.gen.go
  backends/pkg/eventmesh/v1/builder.go
  backends/pkg/eventmesh/v1/builder_test.go
  backends/pkg/eventmesh/v1/endpoint.go
  backends/pkg/eventmesh/v1/eventtype.go
  backends/pkg/eventmesh/v1/server.gen.go
  backends/pkg/eventmesh/v1/source.go
  backends/pkg/eventmesh/v1/subscribable.go
  backends/pkg/util/util.go
  backstage/plugins/knative-event-mesh-backend/DEVELOPMENT.md
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProvider.test.ts
  backstage/plugins/knative-event-mesh-backend/src/providers/knativeEventMeshProvider.ts
  go.mod
  specs/event-mesh-v1.yaml
  test/config/eventmesh-backend-user.yaml
  test/e2e-common.sh
Labels: size/XXL, approved, lgtm
